spring:
  profiles:
    active: dev

# Datasource Configurations
h2:
  console:
    enabled: true
    path: /h2

---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:h2:mem:///db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: root
    password: root
    initialization-mode: always