spring:
  application:
    name: springboot-webflux-api-aggregator-service
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost
    preferIpAddress: true


resilience4j:
  circuitbreaker:
    instances:
      getAddress:
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50